CREATE TABLE FUNCTION_USAGE_LOG (
    ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MARK NUMBER(2),
    SUBJECT_COUNT NUMBER(10),
    FUNCTION_CALLS NUMBER(10)
);

DROP TABLE FUNCTION_USAGE_LOG;

DROP PACKAGE MY_PACK;

CREATE OR REPLACE PACKAGE my_pack AS
    FUNCTION count_subjects (mark NUMBER) RETURN NUMBER;
    PROCEDURE logs;
    call_count NUMBER := 0;
    last_mark NUMBER;
    last_subject_count NUMBER := 0;
END my_pack;

CREATE OR REPLACE PACKAGE BODY my_pack AS
    FUNCTION count_subjects(mark NUMBER) RETURN NUMBER IS
        subject_count NUMBER := 0;
    BEGIN
        SELECT COUNT(*)
        INTO subject_count
        FROM (SELECT SUBJ_ID
              FROM EXAMS
              WHERE MARK = mark
              GROUP BY SUBJ_ID
              HAVING COUNT(STUD_ID) > 3);

        call_count := call_count + 1;
        last_mark := mark;

        last_subject_count := SUBJECT_COUNT;
        RETURN subject_count;
    END count_subjects;

    PROCEDURE logs IS
    BEGIN
        INSERT INTO FUNCTION_USAGE_LOG (MARK, SUBJECT_COUNT, FUNCTION_CALLS)
        VALUES (last_mark, last_subject_count, call_count);

        COMMIT;
    END logs;

END my_pack;

set SERVEROUTPUT ON;
set timing on;

DECLARE
    SUBJECT_COUNT NUMBER;
BEGIN
    SUBJECT_COUNT := MY_PACK.COUNT_SUBJECTS(MARK  => 5 /*IN NUMBER*/);
    DBMS_OUTPUT.put_line(SUBJECT_COUNT);
end;

BEGIN
    MY_PACK.LOGS();
end;