set SERVEROUTPUT ON;
set timing on;

CREATE TABLE LECTURER_LAB (
    LECTURER_ID INTEGER PRIMARY KEY,
    SURNAME CHAR(30) NOT NULL,
    NAME CHAR(30) NOT NULL,
    CITY CHAR(30) NOT NULL,
    UNIV_ID INTEGER
);

CREATE SEQUENCE LECTURER_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

-- DROP SEQUENCE LECTURER_SEQ;

INSERT INTO LECTURER_LAB (LECTURER_ID, SURNAME, NAME, CITY, UNIV_ID)
VALUES (LECTURER_SEQ.NEXTVAL, 'Ivanov', 'Ivan', 'Moscow', 1);

INSERT INTO LECTURER_LAB (LECTURER_ID, SURNAME, NAME, CITY, UNIV_ID)
VALUES (LECTURER_SEQ.NEXTVAL, 'Petrov', 'Petr', 'Saint Petersburg', 2);

INSERT INTO LECTURER_LAB (LECTURER_ID, SURNAME, NAME, CITY, UNIV_ID)
VALUES (LECTURER_SEQ.NEXTVAL, 'Sidorov', 'Alexey', 'Novosibirsk', 3);